In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

In [2]:
data_dir = '../Data/big_cats/'
tab1 = pd.read_excel(data_dir + 'BiochemicalChangesinCKDAbbrevColours20160828.xlsx', sheetname='NormalFelidsn=1319')

/Users/ruth/miniconda3/envs/vetAI/lib/python3.7/site-packages/pandas/util/_decorators.py:188: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  return func(*args, **kwargs)

In [3]:
tab1[tab1['ARKS Number']==900485]

,ID,ARKS Number,Animal Name,Species,Date,Low USG?,urea (mmol/L),Uraemia,Creatinine (umol/L),Hypercreatinaemia?,Total Plasma Protein (g/L),hyperproteinaemia,Serum Albumin (g/L),hyperalbuminaemia,Globulins (g/L),Changes in globulins,Haematocrit (%),Anaemic?,Potassium (mmol/L),Changes in potassium,Calcium (mmol/L),Changes in calcium,Phosphate (mmol/L),Hyperphosphataemia?,Sodium (mmol/L),Changes in sodium,Chloride (mmol/L),Changes in chloride,Bicarbonate,Changes in bicarbonate,Glucose,CK (U/L),ALP (U/L),ALT (U/L),AST,Amylase,-,Cholesterol (mmol/L),Bilirubin,Serum/plasma appearance,Comments:
0,473,900485,Omaha,Snow leopard,1995-10-30,False,7.5,False,170,False,72,normal,32,normal,40,normal,43,normal,3.9,normal,2.6,normal,1.3,normal,155,normal,123,normal,9.6,normal,9,693,22,30,59,4824,-,-,-,-,-
1,64,900485,Omaha,Snow leopard,1995-08-28,False,11.6,False,190,False,67,normal,34,normal,33,normal,46,normal,4.1,normal,2.8,normal,1.4,normal,154,normal,120,normal,9.8,normal,10.7,89,32,51,18,5484,-,-,-,-,-
17,65,900485,Omaha,Snow leopard,1996-10-11,False,9.8,False,180,False,69,normal,33,normal,36,normal,44,normal,4.1,normal,2.4,normal,1.5,normal,149,normal,119,normal,11.5,normal,8.2,151,28,44,19,5181,-,-,-,-,-
18,70,900485,Omaha,Snow leopard,2000-11-01,False,8.8,False,220,False,66,normal,34,normal,32,normal,45,normal,4.5,normal,2.5,normal,1.5,normal,156,normal,126,normal,11.5,normal,10.2,248,26,65,26,-,-,-,-,-,-
20,66,900485,Omaha,Snow leopard,1997-01-08,False,7.5,False,180,False,72,normal,34,normal,38,normal,40,normal,4.4,normal,2.6,normal,1.4,normal,153,normal,115,normal,11.9,normal,6.7,156,26,47,21,5139,-,-,-,-,-
25,67,900485,Omaha,Snow leopard,1997-05-14,False,8.9,False,190,False,71,normal,32,normal,39,normal,42,normal,4.1,normal,2.6,normal,1.4,normal,151,normal,117,normal,12,normal,11.5,227,23,44,19,5350,-,-,-,-,-
39,69,900485,Omaha,Snow leopard,2000-01-18,False,8.9,False,190,False,71,normal,34,normal,37,normal,46,normal,4.2,normal,2.5,normal,1.4,normal,145,normal,113,normal,12.9,normal,7.8,217,25,57,27,-,-,-,-,-,-
163,68,900485,Omaha,Snow leopard,1997-10-03,False,8.2,False,240,False,70,normal,31,normal,39,normal,49,normal,4.7,normal,2.6,normal,1.8,normal,151,normal,115,normal,15.8,normal,5.4,112,24,50,23,5308,-,-,-,-,-
1096,1615,900485,Omaha,Snow leopard,2004-05-29,False,14.25,False,192,False,86,normal,33,normal,53,normal,29,normal,-,-,2.32,normal,1.48,normal,-,-,-,-,-,-,14.2,-,32,23,-,2361,normal,3.8,10,-,-
1184,71,900485,Omaha,Snow leopard,2001-04-11,False,10.03,False,294,False,72,normal,38,normal,34,normal,45,normal,-,-,-,-,1.6,normal,-,-,-,-,-,-,11.7,237,31,48,32,-,-,-,-,-,-

In [19]:
tab2 = pd.read_excel('BiochemicalChangesinCKDAbbrevColours20160828.xlsx', sheetname='CKDn=163')

In [26]:
tab2[tab2['ARKS Number']==850083]

,ID,ARKS Number,Animal Name,Species,Date,Low USG?,urea (mmol/L),Uraemia,Creatinine (umol/L),Hypercreatinaemia?,...,CK (U/L),ALP (U/L),ALT (U/L),AST,Amylase,-,Cholesterol (mmol/L),Bilirubin,Serum/plasma appearance,Comments:
1,306,850083,Shiva,Tiger,2002-02-27,True,36.9,azotaemia,654,hypercreatininaemia,...,345,32,57,48,-,-,-,-,-,"Depressed, anorexic. GA - Fliuds, anabolic st,..."
6,305,850083,Shiva,Tiger,2001-06-29,True,11.4,False,385,hypercreatininaemia,...,301,29,104,88,-,-,-,-,-,-
8,308,850083,Shiva,Tiger,2002-03-08,True,30.3,azotaemia,786,hypercreatininaemia,...,390,28,84,41,-,-,-,-,-,-

In [37]:
tab2

,ID,ARKS Number,Animal Name,Species,Date,Low USG?,urea (mmol/L),Uraemia,Creatinine (umol/L),Hypercreatinaemia?,Total Plasma Protein (g/L),hyperproteinaemia,Serum Albumin (g/L),hyperalbuminaemia,Globulins (g/L),Changes in globulins,Haematocrit (%),Anaemic?,Potassium (mmol/L),Changes in potassium,Calcium (mmol/L),Changes in calcium,Phosphate (mmol/L),Hyperphosphataemia?,Sodium (mmol/L),Changes in sodium,Chloride (mmol/L),Changes in chloride,Bicarbonate,Changes in bicarbonate,Glucose,CK (U/L),ALP (U/L),ALT (U/L),AST,Amylase,-,Cholesterol (mmol/L),Bilirubin,Serum/plasma appearance,Comments:
0,1604,890254,Mangar,Snow leopard,2008-12-29,False,123,azotaemia,-,,-,-,41,normal,-,normal,37,normal,-,-,-,-,8.4,hyperphosphataemia,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
1,306,850083,Shiva,Tiger,2002-02-27,True,36.9,azotaemia,654,hypercreatininaemia,92,hyperproteinaemia,36,normal,56,hyperglobulinaemia,45,normal,3.9,normal,-,-,2.68,normal,150,normal,-,-,11.6,normal,11.95,345,32,57,48,-,-,-,-,-,"Depressed, anorexic. GA - Fliuds, anabolic st,..."
2,1430,A70193,Mujambi,Lion,2011-12-23,False,17.8,False,463,hypercreatininaemia,70.6,normal,32.7,normal,37.9,normal,38,normal,4.6,normal,-,-,-,-,147,normal,115,normal,15,normal,4.3,28,10,54,32,-,-,-,-,-,-
3,37,920185,Chester,Tiger,2000-05-05,True,17.2,False,380,hypercreatininaemia,87,hyperproteinaemia,-,normal,-,normal,45,normal,3.85,normal,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
4,36,920185,Chester,Tiger,1999-09-17,True,15.9,False,387,hypercreatininaemia,70,normal,-,normal,-,normal,36,normal,3.99,normal,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
5,35,920185,Chester,Tiger,1999-09-15,True,29.7,azotaemia,526,hypercreatininaemia,94,hyperproteinaemia,-,normal,-,normal,48,normal,3.35,hypokalaemia,-,-,-,-,-,-,-,-,-,-,-,165,-,-,51.3,-,-,-,-,-,isosthenuric urine
6,305,850083,Shiva,Tiger,2001-06-29,True,11.4,False,385,hypercreatininaemia,79,normal,33,normal,47,normal,48,normal,-,-,-,-,1.68,normal,-,-,-,-,-,-,11.9,301,29,104,88,-,-,-,-,-,-
7,467,A20021,Cantik,Fishing cat,2004-04-16,False,11.66,False,285,hypercreatininaemia,60,normal,27,normal,33,normal,37,normal,-,-,-,-,1.56,normal,-,-,-,-,-,-,6.67,3472,19,41,133,-,-,-,-,-,-
8,308,850083,Shiva,Tiger,2002-03-08,True,30.3,azotaemia,786,hypercreatininaemia,88,hyperproteinaemia,37,normal,52,hyperglobulinaemia,43,normal,-,-,-,-,2.46,normal,-,-,-,-,-,-,11.1,390,28,84,41,-,-,-,-,-,-
9,77,930430,Samar,Clouded leopard,2004-03-04,True,29.8,azotaemia,240,hypercreatininaemia,106,hyperproteinaemia,32,normal,73,hyperglobulinaemia,33,normal,-,-,-,-,2.21,normal,-,-,-,-,-,-,8.55,105,37,437,138,-,-,-,-,-,-
10,76,930430,Samar,Clouded leopard,2003-12-23,True,7.64,False,242,hypercreatininaemia,103,hyperproteinaemia,30,normal,73,hyperglobulinaemia,35,normal,-,-,-,-,2,normal,-,-,-,-,-,-,9.49,-,25,142,26,-,-,-,-,-,-
11,516,700022,Gai,Tiger,1990-01-02,False,29.6,azotaemia,-,-,95,hyperproteinaemia,-,normal,-,normal,38,normal,-,-,-,-,-,-,-,-,-,-,-,-,7.2,-,-,-,-,-,-,-,-,-,-
12,967,921430,Chad,Caracal,2001-06-18,True,16.7,azotaemia,311,hypercreatininaemia,76,normal,-,normal,-,normal,38,normal,-,-,-,-,-,-,-,-,-,-,-,-,7.2,-,-,-,34.5,-,-,-,-,-,-
13,1391,A49221,Askari,Cheetah,2013-03-27,True,40.1,azotaemia,1763,hypercreatininaemia,71.5,normal,31.1,normal,40.4,normal,47,normal,-,-,-,-,-,-,-,-,-,-,-,-,5.9,322,-,57,60,-,-,-,-,-,-
14,1390,A49221,Askari,Cheetah,2013-03-07,False,40.1,azotaemia,550,hypercreatininaemia,78,normal,31.6,normal,46.4,normal,44,normal,-,-,-,-,-,-,-,-,-,-,-,-,5.1,155,-,122,71,-,-,-,-,-,-
15,177,pet,Rajah,Tiger,1992-02-27,True,83,azotaemia,698,hypercreatininaemia,-,-,-,normal,-,normal,29,normal,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
16,1357,A10134,Tigerboy,Tiger,2008-05-22,True,44.2,azotaemia,672,hypercreatininaemia,95.8,hyperproteinaemia,43.2,normal,52.6,hyperglobulinaemia,46,normal,-,-,-,-,-,-,-,-,-,-,-,-,8,-,-,151,70,-,-,-,-,-,-
17,1404,A70551,Assiqua,Tiger,2008-12-19,True,16,False,482,hypercreatininaemia,86.1,hyperproteinaemia,32.4,normal,53.7,hyperglobulinaemia,31,normal,-,-,-,-,-,-,-,-,-,-,-,-,-,187,-,102,61,-,-,-,-,-,-
18,1371,999025,Induna,Cheetah,2010-02-05,False,34,azotaemia,429,hypercreatininaemia,70,normal,35.7,normal,34.3,normal,-,-,-,-,-,-,-,-,-,-,-,-,-,-,6.3,40,-,88,128,-,-,-,-,-,-
19,1393,A49221,Askari,Cheetah,2013-03-22,False,40.8,azotaemia,896,hypercreatininaemia,73.9,normal,31.9,normal,42,normal,-,-,-,-,-,-,-,-,-,-,-,-,-,-,5.7,173,-,91,53,-,-,-,-,-,-
20,1374,999025,Induna,Cheetah,2010-07-26,False,40.8,azotaemia,452,hypercreatininaemia,75.5,normal,32,normal,43.5,normal,-,-,-,-,-,-,-,-,-,-,-,-,-,-,14.8,91,-,137,107,-,-,-,-,-,-
21,1379,A10083,Kifani,Cheetah,2010-09-27,False,49.2,azotaemia,554,hypercreatininaemia,73.4,normal,29.4,normal,44,normal,-,-,-,-,-,-,-,-,-,-,-,-,-,-,0.23,266,-,307,318,-,-,-,-,-,-
22,1402,A70551,Assiqua,Tiger,2013-07-05,False,6.6,False,370,hypercreatininaemia,77.7,normal,37.4,normal,40.3,normal,-,-,-,-,-,-,-,-,-,-,-,-,-,-,10.2,138,-,60,39,-,-,-,-,-,-
23,1431,A70193,Mujambi,Lion,2014-06-03,False,18.2,False,379,hypercreatininaemia,76,normal,23,normal,53,normal,-,-,-,-,-,-,-,-,-,-,-,-,-,-,15.5,85,-,43,44,-,-,-,-,-,-
24,1591,MGServal3,Ngambi,Serval,2008-12-15,False,46,azotaemia,-,,-,-,-,normal,-,normal,-,-,-,-,-,-,-,-,-,-,-,-,-,-,167,-,-,148,-,-,-,-,-,-,"high urea, ALT and glucose in mg/dl. Euthanased"
25,1825,A02062,Robi,Cheetah,2011-12-22,False,90,azotaemia,-,-,-,-,-,normal,-,normal,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
26,832,Koyukon,Koyukon,Northern lynx,1988-06-01,True,11.85,False,319,hypercreatininaemia,-,-,-,normal,-,normal,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,1432,-,-,-,-,-,-,-,-,-
27,812,790038,Poetry,Tiger,1997-11-22,True,-,-,884,hypercreatininaemia,-,-,-,normal,-,normal,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
28,1398,A60598,Tuan,Tiger,2014-04-01,False,15.1,False,390,hypercreatininaemia,89.5,hyperproteinaemia,45.5,hyperalbuminaemia,44,normal,-,-,-,-,-,-,-,-,-,-,-,-,-,-,6.4,153,-,45,32,-,-,-,-,-,-
29,1377,999025,Induna,Cheetah,2010-08-19,False,40.5,azotaemia,547,hypercreatininaemia,81.1,hyperproteinaemia,31.7,normal,49.4,hyperglobulinaemia,-,-,-,-,-,-,-,-,-,-,-,-,-,-,14.3,329,-,86,79,-,-,-,-,-,-
30,1354,999024,Nadonda,Cheetah,2007-08-17,True,45.3,azotaemia,1651,hypercreatininaemia,92,hyperproteinaemia,42.8,normal,49.2,hyperglobulinaemia,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
31,1369,999027,Lula,Cheetah,2009-09-28,False,57.5,azotaemia,744,hypercreatininaemia,94.8,hyperproteinaemia,32.6,normal,62.2,hyperglobulinaemia,-,-,-,-,-,-,-,-,-,-,-,-,-,-,9.5,125,-,173,99,-,-,-,-,-,-
32,1358,A10134,Tigerboy,Tiger,2008-05-28,True,85.9,azotaemia,652,hypercreatininaemia,99.8,hyperproteinaemia,35.6,normal,64.2,hyperglobulinaemia,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,163,95,-,-,-,-,-,-
33,1368,999027,Lula,Cheetah,2009-07-11,False,93.5,azotaemia,567,hypercreatininaemia,92.6,hyperproteinaemia,37,normal,55.6,hyperglobulinaemia,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,351,-,204,217,-,-,-,-,-,-
34,1361,A60598,Tuan,Tiger,2008-12-19,False,12.5,False,397,hypercreatininaemia,85.4,hyperproteinaemia,31.4,normal,54,hyperglobulinaemia,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,130,-,99,52,-,-,-,-,-,-
35,1392,A49221,Askari,Cheetah,2013-03-03,True,17.4,False,2085,hypercreatininaemia,85.3,hyperproteinaemia,31.9,normal,53.4,hyperglobulinaemia,-,-,-,-,-,-,-,-,-,-,-,-,-,-,5.3,45,-,147,23,-,-,-,-,-,-
36,1412,A10081,Jala,Cheetah,2013-12-02,False,35.1,azotaemia,382,hypercreatininaemia,79.4,normal,31.7,normal,47.7,hyperglobulinaemia,-,-,-,-,-,-,-,-,-,-,-,-,-,-,4,66,-,80,70,-,-,-,-,-,-
37,1388,A49219,Tsotsie,Cheetah,2013-01-25,False,21.1,azotaemia,337,hypercreatininaemia,155,hyperproteinaemia,51,hyperalbuminaemia,104,hyperglobulinaemia,-,-,-,-,-,-,-,-,-,-,-,-,-,-,7.5,227,-,247,151,-,-,-,-,-,-
38,1110,960093,Twande,Cheetah,2004-11-04,True,64,azotaemia,1398,hypercreatininaemia,-,-,-,normal,-,normal,45,normal,-,-,5.2,hypercalcaemia,-,-,157,normal,-,-,16,normal,8.6,-,-,142,-,-,-,-,-,clear,-
39,1109,960093,Twande,Cheetah,2004-11-04,True,112,azotaemia,1388,hypercreatininaemia,89,hyperproteinaemia,49,hyperalbuminaemia,40,normal,45,normal,5.3,normal,3.63,hypercalcaemia,5.01,hyperphosphataemia,160,normal,118,normal,14,normal,-,1168,3,148,63,-,normal,5,11,clear,"marked azotaemia, dehydration"
40,1108,960093,Twande,Cheetah,2004-10-29,True,74.2,azotaemia,950,hypercreatininaemia,78,normal,43,normal,35,normal,44,normal,3.3,hypokalaemia,3.49,hypercalcaemia,3.12,normal,158,normal,109,hypochloraemia,24,high,6.9,921,5,117,84,-,normal,4.1,3,clear,"azotaemia, hypercalciamia, hyperphospahataeimi..."
41,455,950077,Sarge,Cheetah,1999-01-19,True,60.2,azotaemia,829,hypercreatininaemia,85,hyperproteinaemia,36,normal,49,hyperglobulinaemia,32,normal,4.5,normal,3.48,hypercalcaemia,3.05,normal,157,normal,120,normal,-,-,8.5,131,6,38,5,2109,-,-,4,-,-
42,1107,960093,Twande,Cheetah,2004-10-25,True,75.2,azotaemia,1270,hypercreatininaemia,89,hyperproteinaemia,46,hyperalbuminaemia,43,normal,58,haemoconcentration,3.6,hypokalaemia,3.39,hypercalcaemia,3.96,hyperphosphataemia,159,normal,111,hypochloraemia,19,normal,7.7,512,3,205,141,-,normal,4.7,6,clear,azotaemia and elevated liver enzymes
43,454,950077,Sarge,Cheetah,1999-01-11,True,41.7,azotaemia,569,hypercreatininaemia,90,hyperproteinaemia,39,normal,51,hyperglobulinaemia,38,normal,4.6,normal,3.3,hypercalcaemia,2.15,normal,151,normal,108,hypochloraemia,-,-,4.5,165,8,56,25,1869,-,-,3,-,-
44,457,950077,Sarge,Cheetah,1999-02-09,True,60,azotaemia,748,hypercreatininaemia,84,hyperproteinaemia,35,normal,49,hyperglobulinaemia,31,normal,4.2,normal,3.29,hypercalcaemia,3.22,normal,155,normal,117,normal,-,-,6.6,952,8,80,78,1978,-,-,2,-,-
45,1087,960093,Twande,Cheetah,2004-10-26,True,66,azotaemia,1132,hypercreatininaemia,77,normal,42,normal,35,normal,47,normal,3.5,hypokalaemia,3.23,normal,2.09,normal,167,hypernatraemia,127,normal,22,normal,6.71,3030,3,140,120,-,normal,3.5,3,clear,CKD - uraemic
46,540,950079,Mawimbi,Cheetah,1998-04-16,True,39.3,azotaemia,407,hypercreatininaemia,67,normal,34,normal,33,normal,39,normal,4.3,normal,3.2,normal,1.67,normal,150,normal,112,normal,-,-,6,75,15,359,181,1563,-,-,5,-,-
47,458,950077,Sarge,Cheetah,1998-09-30,False,25.5,azotaemia,343,hypercreatininaemia,84,hyperproteinaemia,35,normal,49,hyperglobulinaemia,28,normal,5.1,normal,3.16,normal,1.94,normal,153,normal,114,normal,-,-,5.3,188,6,29,15,3328,-,-,12,-,-
48,1460,999024,Nadonda,Cheetah,2007-08-20,True,88.9,azotaemia,1338,hypercreatininaemia,89,hyperproteinaemia,44,normal,45,normal,40,normal,4.6,normal,3.15,normal,5.02,hyperphosphataemia,157,normal,119,normal,7,low,-,2013,3,96,84,-,normal,5.5,2,clear,"metabolic acidosis, hyperPhos, hyperCa"
49,1785,A49219,Tsotsie,Cheetah,2014-07-25,False,64.3,azotaemia,1220,hypercreatininaemia,90,hyperproteinaemia,47,hyperalbuminaemia,43,normal,-,-,-,-,3.15,normal,4.53,hyperphosphataemia,156,normal,-,-,-,-,5.9,-,0,185,-,1594,-,-,-,-,-
50,537,950079,Mawimbi,Cheetah,1998-08-04,False,46.9,azotaemia,1072,hypercreatininaemia,83,hyperproteinaemia,34,normal,49,hyperglobulinaemia,33,normal,4.2,normal,3.13,normal,3.13,normal,145,normal,108,hypochloraemia,-,-,7.4,62,3,47,3,1582,-,-,17,-,-
51,456,950077,Sarge,Cheetah,1999-02-02,True,38.8,azotaemia,607,hypercreatininaemia,77,normal,34,normal,43,normal,24,anaemic,4.2,normal,3.1,normal,2.39,normal,153,normal,119,normal,-,-,5.9,60,8,62,30,1939,-,-,2,-,-
52,1095,960095,Sasa,Cheetah,2004-11-17,True,57.8,azotaemia,640,hypercreatininaemia,74,normal,40,normal,34,normal,41,normal,4.1,normal,3.07,normal,2.55,normal,155,normal,126,normal,12,low,-,95,8,116,48,-,normal,5.6,2,clear,-
53,546,950079,Mawimbi,Cheetah,1998-01-23,True,30.5,azotaemia,450,hypercreatininaemia,66,normal,29,normal,37,normal,36,normal,4.7,normal,3,normal,1.9,normal,157,normal,125,normal,14.4,normal,6.1,234,9,101,42,-,-,-,2,-,-
54,539,950079,Mawimbi,Cheetah,1998-08-12,True,62.4,azotaemia,3188,hypercreatininaemia,92,hyperproteinaemia,38,normal,54,hyperglobulinaemia,42,normal,7.1,hyperkalaemia,2.99,normal,8.07,hyperphosphataemia,143,hyponatraemia,90,hypochloraemia,-,-,8,3761,9,155,78,1588,-,-,81,-,-
55,1461,999023,Nymphosa,Cheetah,2007-08-16,False,72.3,azotaemia,854,hypercreatininaemia,73,normal,30,normal,43,normal,34,normal,4.4,normal,2.98,normal,4.71,hyperphosphataemia,158,normal,107,hypochloraemia,20,normal,-,6439,3,143,204,-,normal,4.8,47,icteric 1+,-
56,452,950079,Mawimbi,Cheetah,1998-02-18,True,32.7,azotaemia,399,hypercreatininaemia,70,normal,34,normal,36,normal,35,normal,4.6,normal,2.97,normal,1.97,normal,157,normal,124,normal,-,-,6.9,178,11,121,26,1926,-,-,1,-,-
57,1459,999024,Nadonda,Cheetah,2007-08-22,False,96.4,azotaemia,1358,hypercreatininaemia,62,normal,32,normal,30,normal,-,-,4.4,normal,2.95,normal,5.78,hyperphosphataemia,157,normal,118,normal,9,low,-,-,-,111,-,-,-,-,-,clear,-
58,1096,960095,Sasa,Cheetah,2004-12-01,True,56.7,azotaemia,1130,hypercreatininaemia,65,normal,34,normal,31,normal,38,normal,3.6,hypokalaemia,2.93,normal,3.61,hyperphosphataemia,151,normal,120,normal,11,low,-,1507,4,119,83,-,normal,5.1,13,clear,-
59,1458,999024,Nadonda,Cheetah,2007-08-21,True,98.5,azotaemia,1366,hypercreatininaemia,63,normal,32,normal,31,normal,25,anaemic,5,normal,2.92,normal,5.89,hyperphosphataemia,155,normal,118,normal,12,low,-,-,-,116,-,-,-,-,-,clear,-
60,1121,960094,Haraka,Cheetah,2008-11-11,False,50,azotaemia,774,hypercreatininaemia,67,normal,32,normal,35,normal,31,normal,4.4,normal,2.9,normal,2.94,normal,157,normal,120,normal,14,normal,-,241,5,95,67,-,normal,5.8,5,clear,azotaemia
61,488,A80047,Mtoto,Cheetah,2012-05-18,False,38,azotaemia,448,hypercreatininaemia,69,normal,37,normal,32,normal,-,-,4.9,normal,2.87,normal,1.76,normal,155,normal,122,normal,17,normal,6,137,7,66,36,-,-,-,5,-,-
62,179,pet,Rajah,Tiger,1992-07-30,False,82.2,azotaemia,725,hypercreatininaemia,85,hyperproteinaemia,37,normal,48,normal,26,normal,4.4,normal,2.87,normal,-,-,147,normal,-,-,-,-,7.6,227,-,42,29,-,-,-,-,-,-
63,402,870008,Tsavo,Cheetah,2000-07-28,True,24.4,azotaemia,382,hypercreatininaemia,83,hyperproteinaemia,36,normal,47,normal,36,normal,4.2,normal,2.86,normal,1.79,normal,156,normal,124,normal,-,-,7.5,153,11,272,127,2037,-,-,2,-,-
64,174,A40080,Sunzu,Cheetah,2011-07-25,False,13,False,363,hypercreatininaemia,78,normal,39,normal,39,normal,53,haemoconcentration,8.8,hyperkalaemia,2.85,normal,3.67,hyperphosphataemia,160,normal,117,normal,14,normal,8.8,494,19,113,166,-,-,-,3,-,-
65,218,950075,Zenith,Cheetah,2001-09-06,True,26.6,azotaemia,405,hypercreatininaemia,80,hyperproteinaemia,35,normal,45,normal,43,normal,4.5,normal,2.85,normal,1.53,normal,156,normal,128,normal,-,-,7.9,138,24,86,71,2371,-,-,-,-,-
66,960,921430,Chad,Caracal,2001-05-29,True,24.7,azotaemia,340,hypercreatininaemia,70,normal,35,normal,35,normal,44,normal,4,normal,2.85,hypercalcaemia,1.47,normal,155,normal,118,normal,19,normal,-,152,34,92,30,-,normal,3.2,4,-,-
67,1544,B09072,Masuka,Cheetah,2013-05-04,True,57,azotaemia,698,hypercreatininaemia,78,normal,42,normal,36,normal,27,normal,4.3,normal,2.83,normal,2.38,normal,151,normal,-,-,-,-,6.1,-,4,120,-,1351,-,-,6,-,-
68,1543,B09072,Masuka,Cheetah,2013-04-25,False,53,azotaemia,763,hypercreatininaemia,78,normal,44,normal,34,normal,-,-,4.1,normal,2.83,normal,2.27,normal,147,normal,-,-,-,-,6.5,-,4,116,-,1340,-,-,5,-,-
69,219,950075,Zenith,Cheetah,2001-11-12,False,47.1,azotaemia,834,hypercreatininaemia,99,hyperproteinaemia,34,normal,65,hyperglobulinaemia,42,normal,5.2,normal,2.82,normal,5.33,hyperphosphataemia,153,normal,111,hypochloraemia,-,-,3,100,7,165,114,3824,-,-,-,-,-
70,23,930229,Indira Maha,Lion,2002-07-18,True,41.5,azotaemia,1057,hypercreatininaemia,79,normal,31,normal,48,normal,26,anaemic,4.4,normal,2.82,normal,3.13,hyperphosphataemia,160,normal,129,hyperchloraemia,-,-,9.4,752,7,40,48,1223,-,-,-,-,-
71,197,950078,Dani,Cheetah,2002-12-18,False,33.5,azotaemia,395,hypercreatininaemia,91,hyperproteinaemia,40,normal,51,hyperglobulinaemia,50,normal,3.6,hypokalaemia,2.81,normal,1.63,normal,152,normal,99,hypochloraemia,-,-,9.3,761,4,87,63,1994,-,-,8,-,-
72,1513,999027,Lula,Cheetah,2009-09-26,False,60.7,azotaemia,610,hypercreatininaemia,94,hyperproteinaemia,33,normal,61,hyperglobulinaemia,-,-,5.2,normal,2.8,normal,2.7,normal,156,normal,125,normal,7,low,5.6,93,13,194,102,-,normal,5.4,3,normal,-
73,490,A80047,Mtoto,Cheetah,2012-07-19,False,40,azotaemia,405,hypercreatininaemia,72,normal,37,normal,35,normal,44,normal,4.9,normal,2.79,normal,1.86,normal,156,normal,121,normal,18,normal,5.7,109,9,90,49,-,-,-,-,-,-
74,230,890000,Audrey,Lion,2001-03-01,True,40.9,azotaemia,1208,hypercreatininaemia,79,normal,30,normal,49,normal,46,normal,4,normal,2.79,normal,2.64,normal,150,normal,118,normal,-,-,9.9,187,10,15,2,1254,-,-,-,-,-
75,178,pet,Rajah,Tiger,1992-07-28,False,84,azotaemia,692,hypercreatininaemia,83,normal,35,normal,48,normal,-,-,4.8,normal,2.79,normal,-,-,156,normal,-,-,-,-,7.8,-,-,-,-,-,-,-,-,-,-
76,1552,A49219,Tsotsie,Cheetah,2014-07-30,False,63.2,azotaemia,1225,hypercreatininaemia,80,hyperproteinaemia,44,normal,36,normal,39,normal,3.3,hypokalaemia,2.78,normal,3.19,normal,151,normal,-,-,-,-,5.6,-,4,125,-,1317,-,-,8,-,-
77,1122,960094,Haraka,Cheetah,2008-05-28,True,27.4,azotaemia,397,hypercreatininaemia,74,normal,40,normal,34,normal,43,normal,4.8,normal,2.77,normal,1.71,normal,162,normal,125,normal,21,normal,-,379,19,1301,947,-,normal,7.5,4,clear,hepatocellular damage
78,203,950078,Dani,Cheetah,2008-09-05,False,67.7,azotaemia,671,hypercreatininaemia,79,normal,34,normal,45,normal,35,normal,4.1,normal,2.77,normal,2.58,normal,159,normal,123,normal,-,-,7.9,103,8,224,94,2028,-,-,3,-,-
79,401,870008,Tsavo,Cheetah,2000-08-21,True,55.3,azotaemia,1032,hypercreatininaemia,109,hyperproteinaemia,36,normal,73,hyperglobulinaemia,41,normal,3.8,normal,2.76,normal,4.78,hyperphosphataemia,148,normal,113,normal,-,-,8.2,2827,10,625,260,3329,-,-,5,-,-
80,1269,890114,Maya,Jaguar,2008-11-20,True,44.9,azotaemia,392,hypercreatininaemia,86,hyperproteinaemia,37,normal,49,normal,40,normal,4.7,normal,2.76,normal,1.97,normal,154,normal,126,normal,12,normal,6.8,400,8,107,74,-,normal,6.9,2,clear,-
81,1922,880014,Claudius,Cheetah,1997-01-16,True,16.3,False,399,hypercreatininaemia,81,hyperproteinaemia,34,normal,47,normal,47,normal,-,-,2.75,normal,1.45,normal,-,-,-,-,-,-,6.0495,149,24,155,79,-,normal,0,4.0014,-,-
82,1652,950061,Mohan,Tiger,2012-06-06,True,46.4,azotaemia,925,hypercreatininaemia,99,hyperproteinaemia,40,normal,59,hyperglobulinaemia,48,normal,3.3,hypokalaemia,2.74,normal,4.97,hyperphosphataemia,158,normal,113,normal,-,-,9.2,-,21,132,-,-,normal,9.6,12,-,-
83,580,A10080,Shakkari,Cheetah,2012-02-07,True,19.1,False,419,hypercreatininaemia,74,normal,36,normal,38,normal,51,normal,4.2,normal,2.74,normal,2.24,normal,155,normal,115,normal,16,normal,5.3,153,14,92,62,-,-,-,1,-,-
84,1338,A49219,Tsotsie,Cheetah,2014-07-15,False,51,azotaemia,570,hypercreatininaemia,80,hyperproteinaemia,46,hyperalbuminaemia,34,normal,-,-,4.3,normal,2.73,normal,2.02,normal,151,normal,-,-,-,-,6.2,-,9,146,-,1680,-,-,7,-,-
85,81,930430,Samar,Clouded leopard,2004-09-08,True,38,azotaemia,395,hypercreatininaemia,106,hyperproteinaemia,33,normal,73,hyperglobulinaemia,30,normal,4.1,normal,2.72,normal,3.04,hyperphosphataemia,145,normal,114,normal,12,normal,8.42,182,44,858,116,-,-,-,-,-,-
86,489,A80047,Mtoto,Cheetah,2012-08-17,True,38.8,azotaemia,393,hypercreatininaemia,71,normal,36,normal,35,normal,41,normal,4.4,normal,2.72,normal,1.62,normal,149,normal,116,normal,16,normal,5.5,447,9,61,44,-,-,-,-,-,-
87,827,750005,Katamai,Northern lynx,1995-02-08,True,35.1,azotaemia,300,hypercreatininaemia,78,normal,30,normal,48,normal,38,normal,3.8,normal,2.71,normal,1.57,normal,155,normal,124,normal,18,normal,-,1473,29,62,51,-,normal,2.9,8,-,-
88,1554,A20021,Cantik,Fishing cat,2015-08-24,True,61.2,azotaemia,620,hypercreatininaemia,-,-,32,normal,-,normal,-,-,6.4,hyperkalaemia,2.7,normal,3.77,hyperphosphataemia,150,normal,120,normal,-,-,-,-,-,-,-,-,-,-,-,-,-

In [28]:
def intersection(lst1, lst2): 
    return list(set(lst1) & set(lst2))

In [31]:
intersection(tab2['ARKS Number'].values, tab1['ARKS Number'].values)

['A20062',
 890114,
 900485,
 880014,
 890254,
 'A20021',
 890000,
 890004,
 790038,
 900248,
 970009,
 'A10083',
 980123,
 960029,
 'A49219',
 'B00021',
 850083,
 'A10081',
 960035,
 'A40004',
 'Koyukon',
 950061,
 980910,
 'A49221',
 'A10134',
 980912,
 930228,
 930229,
 750005,
 670005,
 950075,
 'A10080',
 950077,
 'A80047',
 950079,
 950078,
 'A50433',
 'B09072',
 830014,
 960069,
 800074,
 'A60598',
 990293,
 921430,
 'A40080',
 840026,
 960093,
 960094,
 960095,
 'A40003',
 780001,
 840034,
 'A50189',
 'A70551',
 'A70193',
 999023,
 999024,
 999025,
 'A10174',
 999027,
 980084,
 870008,
 920185,
 'A40005',
 950908,
 930430]

In [39]:
tab2[tab2['ARKS Number']==900485]

,ID,ARKS Number,Animal Name,Species,Date,Low USG?,urea (mmol/L),Uraemia,Creatinine (umol/L),Hypercreatinaemia?,Total Plasma Protein (g/L),hyperproteinaemia,Serum Albumin (g/L),hyperalbuminaemia,Globulins (g/L),Changes in globulins,Haematocrit (%),Anaemic?,Potassium (mmol/L),Changes in potassium,Calcium (mmol/L),Changes in calcium,Phosphate (mmol/L),Hyperphosphataemia?,Sodium (mmol/L),Changes in sodium,Chloride (mmol/L),Changes in chloride,Bicarbonate,Changes in bicarbonate,Glucose,CK (U/L),ALP (U/L),ALT (U/L),AST,Amylase,-,Cholesterol (mmol/L),Bilirubin,Serum/plasma appearance,Comments:
115,72,900485,Omaha,Snow leopard,2003-09-11,True,19.7,azotaemia,330,hypercreatininaemia,73,normal,35,normal,38,normal,50,haemoconcentration,4.1,normal,2.5,normal,1.3,normal,156,normal,126,normal,10,normal,9.9,207,22,44,14,-,normal,3.7,-,-,-
136,1606,900485,Omaha,Snow leopard,2004-05-16,False,12.8,False,306,hypercreatininaemia,74,normal,36,normal,37,normal,28,normal,-,-,2.39,normal,1.26,normal,-,-,-,-,-,-,9.9,-,26,32,-,2500,normal,4.1,12,-,-

In [40]:
tab1[tab1['ARKS Number']==900485]

,ID,ARKS Number,Animal Name,Species,Date,Low USG?,urea (mmol/L),Uraemia,Creatinine (umol/L),Hypercreatinaemia?,Total Plasma Protein (g/L),hyperproteinaemia,Serum Albumin (g/L),hyperalbuminaemia,Globulins (g/L),Changes in globulins,Haematocrit (%),Anaemic?,Potassium (mmol/L),Changes in potassium,Calcium (mmol/L),Changes in calcium,Phosphate (mmol/L),Hyperphosphataemia?,Sodium (mmol/L),Changes in sodium,Chloride (mmol/L),Changes in chloride,Bicarbonate,Changes in bicarbonate,Glucose,CK (U/L),ALP (U/L),ALT (U/L),AST,Amylase,-,Cholesterol (mmol/L),Bilirubin,Serum/plasma appearance,Comments:
0,473,900485,Omaha,Snow leopard,1995-10-30,False,7.5,False,170,False,72,normal,32,normal,40,normal,43,normal,3.9,normal,2.6,normal,1.3,normal,155,normal,123,normal,9.6,normal,9,693,22,30,59,4824,-,-,-,-,-
1,64,900485,Omaha,Snow leopard,1995-08-28,False,11.6,False,190,False,67,normal,34,normal,33,normal,46,normal,4.1,normal,2.8,normal,1.4,normal,154,normal,120,normal,9.8,normal,10.7,89,32,51,18,5484,-,-,-,-,-
17,65,900485,Omaha,Snow leopard,1996-10-11,False,9.8,False,180,False,69,normal,33,normal,36,normal,44,normal,4.1,normal,2.4,normal,1.5,normal,149,normal,119,normal,11.5,normal,8.2,151,28,44,19,5181,-,-,-,-,-
18,70,900485,Omaha,Snow leopard,2000-11-01,False,8.8,False,220,False,66,normal,34,normal,32,normal,45,normal,4.5,normal,2.5,normal,1.5,normal,156,normal,126,normal,11.5,normal,10.2,248,26,65,26,-,-,-,-,-,-
20,66,900485,Omaha,Snow leopard,1997-01-08,False,7.5,False,180,False,72,normal,34,normal,38,normal,40,normal,4.4,normal,2.6,normal,1.4,normal,153,normal,115,normal,11.9,normal,6.7,156,26,47,21,5139,-,-,-,-,-
25,67,900485,Omaha,Snow leopard,1997-05-14,False,8.9,False,190,False,71,normal,32,normal,39,normal,42,normal,4.1,normal,2.6,normal,1.4,normal,151,normal,117,normal,12,normal,11.5,227,23,44,19,5350,-,-,-,-,-
39,69,900485,Omaha,Snow leopard,2000-01-18,False,8.9,False,190,False,71,normal,34,normal,37,normal,46,normal,4.2,normal,2.5,normal,1.4,normal,145,normal,113,normal,12.9,normal,7.8,217,25,57,27,-,-,-,-,-,-
163,68,900485,Omaha,Snow leopard,1997-10-03,False,8.2,False,240,False,70,normal,31,normal,39,normal,49,normal,4.7,normal,2.6,normal,1.8,normal,151,normal,115,normal,15.8,normal,5.4,112,24,50,23,5308,-,-,-,-,-
1096,1615,900485,Omaha,Snow leopard,2004-05-29,False,14.25,False,192,False,86,normal,33,normal,53,normal,29,normal,-,-,2.32,normal,1.48,normal,-,-,-,-,-,-,14.2,-,32,23,-,2361,normal,3.8,10,-,-
1184,71,900485,Omaha,Snow leopard,2001-04-11,False,10.03,False,294,False,72,normal,38,normal,34,normal,45,normal,-,-,-,-,1.6,normal,-,-,-,-,-,-,11.7,237,31,48,32,-,-,-,-,-,-